# Site settings
title: 7Targets Documentation
email: info@7targets.com
description: >
  7Targets AI Assistant Documentation 
lang: en-US

baseurl: "/7targets-docs/docs" # the subpath of your site, e.g. /blog/
url: https://7targets.github.io/7targets-docs # the base hostname & protocol for your site

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _releases
    type: releases
  values:
    layout: releases
    sectionid: releases
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  releases:
    permalink: /:collection/:path/
    output: true    
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
